"use client";
import { ArrowUp, Check, Clock3, ExternalLink, Mic, MoreHorizontal, Search, Sparkles } from "lucide-react";
import { FormEvent, useState } from "react";
import type { AgentResponse, JourneyTask, MemoryRecord, ResearchResult, TaskStatus } from "../../shared/types/contracts";
import { Button } from "@/components/ui/button";

const demoTasks: JourneyTask[] = [
  { id: "1", title: "Define the move", description: "Confirm Seattle neighborhood, date, household size, and budget.", status: "completed" },
  { id: "2", title: "Research movers", description: "Compare licensed movers and request matching quotes.", status: "researching" },
  { id: "3", title: "Set up utilities", description: "Map electricity, water, gas, and transfer dates.", status: "todo" },
  { id: "4", title: "Handle DMV", description: "Check Washington license and registration deadlines.", status: "waiting" },
  { id: "5", title: "Connect internet", description: "Compare service at the new address.", status: "todo" },
];
const demoResearch: ResearchResult[] = [{ id: "r1", source: "wa.gov", title: "New resident checklist", summary: "Washington publishes a staged checklist for license and vehicle registration changes.", confidence: .92, retrieved_at: new Date().toISOString() }, { id: "r2", source: "utilities.example", title: "Seattle utility setup", summary: "Service availability and lead time depend on the exact street address.", confidence: .76, retrieved_at: new Date().toISOString() }];
const demoMemories: MemoryRecord[] = [{ id: "m1", user_id: "demo", kind: "preference", content: "Prefers morning appointments", created_at: new Date().toISOString(), updated_at: new Date().toISOString() }, { id: "m2", user_id: "demo", kind: "constraint", content: "Moving budget is $4,000", created_at: new Date().toISOString(), updated_at: new Date().toISOString() }];
const columns: { key: TaskStatus; label: string; tone: string }[] = [{ key: "todo", label: "To do", tone: "bg-slate-400" }, { key: "researching", label: "Researching", tone: "bg-lilac" }, { key: "waiting", label: "Waiting", tone: "bg-amber-400" }, { key: "completed", label: "Completed", tone: "bg-emerald-400" }];

export default function Dashboard() {
  const [goal, setGoal] = useState("I am moving to Seattle"); const [result, setResult] = useState<AgentResponse | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const tasks = result?.journey.tasks ?? demoTasks; const research = result?.research ?? demoResearch; const memories = result ? [...result.memories_saved, ...result.memories_used] : demoMemories;
  async function submit(event: FormEvent) { event.preventDefault(); if (!goal.trim()) return; setLoading(true); setError(""); try { const response = await fetch("/api/agent", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ user_id: "demo-user", session_id: "web-demo", message: goal }) }); if (!response.ok) throw new Error((await response.json()).detail ?? "Request failed"); setResult(await response.json()); } catch (caught) { setError(caught instanceof Error ? caught.message : "Agent unavailable"); } finally { setLoading(false); } }
  return <main className="relative min-h-screen p-3 lg:h-screen lg:overflow-hidden">
    <header className="mb-3 flex h-14 items-center justify-between rounded-2xl border border-line bg-panel/90 px-5"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-[10px] bg-acid text-ink"><Sparkles size={17}/></span><span className="font-[var(--font-display)] text-lg font-bold">MyMinion</span><span className="hidden rounded-md border border-lilac/25 bg-lilac/10 px-2 py-1 text-[9px] font-bold uppercase tracking-[.18em] text-lilac sm:block">Agent online</span></div><div className="flex items-center gap-3 text-xs text-zinc-400"><span className="size-2 rounded-full bg-emerald-400 shadow-[0_0_10px_#62d6a6]"/>Voice ready<div className="grid size-8 place-items-center rounded-full bg-gradient-to-br from-lilac to-indigo-700 font-bold text-white">TD</div></div></header>
    <div className="grid gap-3 lg:h-[calc(100vh-86px)] lg:grid-cols-[280px_minmax(520px,1fr)_320px] lg:grid-rows-[minmax(0,1fr)_180px]">
      <section className="flex min-h-[500px] flex-col rounded-2xl border border-line bg-panel/90 p-4 lg:row-span-2"><SectionTitle title="Conversation"/><div className="flex-1 space-y-4 overflow-y-auto py-4"><Bubble mine text={goal}/><Bubble text={result?.message ?? "I’ve built a moving journey. I’m researching the time-sensitive pieces now, and I’ll keep the checklist moving as decisions are made."}/>{error && <p className="rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-xs text-red-300">{error}</p>}</div><form onSubmit={submit} className="rounded-2xl border border-line bg-ink p-3 shadow-glow"><textarea value={goal} onChange={event => setGoal(event.target.value)} className="h-20 w-full resize-none bg-transparent text-sm outline-none placeholder:text-zinc-600" placeholder="Tell me what you need to get done…"/><div className="flex justify-between"><Button type="button" variant="ghost" size="icon" aria-label="Start voice"><Mic size={18}/></Button><Button size="icon" disabled={loading} aria-label="Send goal">{loading ? <span className="size-4 animate-spin rounded-full border-2 border-ink border-t-transparent"/> : <ArrowUp size={18}/>}</Button></div></form></section>
      <section className="min-w-0 rounded-2xl border border-line bg-panel/90 p-4"><div className="mb-5 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-lilac">Active journey</p><h1 className="mt-1 font-[var(--font-display)] text-2xl font-bold">{result?.journey.goal ?? "Move to Seattle"}</h1></div><Button variant="ghost" size="icon"><MoreHorizontal size={18}/></Button></div><div className="grid gap-3 overflow-x-auto pb-2 md:grid-cols-4">{columns.map(column => <div key={column.key} className="min-w-[160px]"><div className="mb-3 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-wider text-zinc-400"><span className={`size-2 rounded-full ${column.tone}`}/>{column.label}<span className="ml-auto text-zinc-600">{tasks.filter(task => task.status === column.key).length}</span></div><div className="space-y-2">{tasks.filter(task => task.status === column.key).map(task => <article key={task.id} className="rounded-xl border border-line bg-ink/70 p-3 transition hover:-translate-y-0.5 hover:border-zinc-600"><p className="text-sm font-semibold">{task.title}</p><p className="mt-2 text-[11px] leading-5 text-zinc-500">{task.description}</p>{task.status === "researching" && <div className="mt-3 h-1 overflow-hidden rounded-full bg-zinc-800"><div className="h-full w-2/3 bg-lilac"/></div>}{task.status === "completed" && <Check className="mt-3 text-emerald-400" size={15}/>}</article>)}</div></div>)}</div></section>
      <section className="rounded-2xl border border-line bg-panel/90 p-4 lg:row-span-2"><SectionTitle title="Research" icon={<Search size={15}/>} /><p className="mt-1 text-xs text-zinc-500">Evidence, not guesses.</p><div className="mt-4 space-y-3 overflow-y-auto lg:max-h-[calc(100vh-170px)]">{research.map(item => <Evidence key={item.id} item={item}/>)}</div></section>
      <section className="rounded-2xl border border-line bg-panel/90 p-4"><div className="mb-3 flex items-center justify-between"><SectionTitle title="Memory timeline"/><span className="text-[10px] text-zinc-600">Long-term · Moss</span></div><div className="flex gap-3 overflow-x-auto">{memories.length ? memories.map(memory => <article key={memory.id} className="min-w-[210px] rounded-xl border border-line bg-ink/70 p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-lilac">{memory.kind.replace("_", " ")}</p><p className="mt-2 text-xs font-medium">{memory.content}</p><p className="mt-3 flex items-center gap-1 text-[9px] text-zinc-600"><Clock3 size={10}/> Saved for future journeys</p></article>) : <p className="text-xs text-zinc-500">No durable memory saved from this message.</p>}</div></section>
    </div>
  </main>;
}
function SectionTitle({ title, icon }: { title: string; icon?: React.ReactNode }) { return <h2 className="flex items-center gap-2 font-[var(--font-display)] text-sm font-bold">{icon}{title}</h2> }
function Bubble({ text, mine = false }: { text: string; mine?: boolean }) { return <div className={mine ? "ml-8 rounded-2xl rounded-tr-md bg-acid p-3 text-xs leading-5 text-ink" : "mr-5 rounded-2xl rounded-tl-md border border-line bg-ink p-3 text-xs leading-5 text-zinc-300"}>{text}</div> }
function Evidence({ item }: { item: ResearchResult }) { return <article className="rounded-xl border border-line bg-ink/70 p-3"><div className="flex items-start justify-between"><span className="text-[9px] font-bold uppercase tracking-wider text-lilac">{Math.round(item.confidence * 100)}% confidence</span><ExternalLink size={12} className="text-zinc-600"/></div><h3 className="mt-2 text-sm font-semibold">{item.title}</h3><p className="mt-2 text-[11px] leading-5 text-zinc-500">{item.summary}</p><p className="mt-3 truncate text-[9px] text-zinc-600">{item.source}</p></article> }
